#!/usr/bin/env bash

if [ "`git rev-parse --show-toplevel`" != "$PWD" ]; then
    echo "Invoke from repo root: ./scripts/$0"
    exit
fi

find . -type f -name "*.js" ! -path "./node_modules/*" ! -path "./public/*" ! -path "./built/*" | xargs node ./node_modules/eslint/bin/eslint.js

./node_modules/tslint/bin/tslint --config "tslint.json" --project tsconfig.json